name: 'c5-deploy-action'
description: 'Executing remote ssh and rsync commands'
author: 'Peter Barry'
inputs:
  host:
    description: 'ssh remote host'
  port:
    description: 'ssh remote port'
    default: 22
  user:
    description: 'ssh user'
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  exclude_from:
    description: 'the name of a local file to exclude, note, should include itself!'
  destination:
    description: 'the path where rsync will use as destination'
  ssh_before:
    description: 'execute commands before rsync'
  ssh_after:
    description: 'execute commands after rsync'
  args:
    description: 'arguments to pass for rsync'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'server'
  color: 'green'
